version: "3.7"
services:
  server:
    build: .
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./src:/usr/src/app/src
      - ./spec:/usr/src/app/spec
      - ./test:/usr/src/app/test
      - ./.env:/usr/src/app/.env
    ports:
      - 8081:8000
